#!/usr/bin/python3
# coding: utf-8
import sys
import os
import argparse
import logging
import json
from staticsite.core import Site

class CmdlineError(RuntimeError):
    pass


def main():
    parser = argparse.ArgumentParser(description="Convert from ikiwiki to hugo.")
    parser.add_argument("srcdir", help="source directory")
    parser.add_argument("destdir", nargs="?", help="destination directory")
    parser.add_argument("-v", "--verbose", action="store_true", help="verbose output")
    parser.add_argument("-t", "--type", action="store", help="output type (dump, hugo, nikola)")

    args = parser.parse_args()

    FORMAT = "%(asctime)-15s %(levelname)s %(message)s"
    if args.verbose:
        logging.basicConfig(level=logging.INFO, stream=sys.stderr, format=FORMAT)
    else:
        logging.basicConfig(level=logging.WARN, stream=sys.stderr, format=FORMAT)

    site = Site(os.path.abspath(os.path.join(args.srcdir, "site")))
    site.read_tree()
    #site.scan()

    # TODO: redo argparse with subcommands

    if args.type == "dump":
        from staticsite.dump import DumpWriter
        if not args.destdir:
            raise CmdlineError("Please provide a destination directory for the dump command")
        writer = DumpWriter(args.destdir)
    elif args.type == "build":
        from staticsite.web import WebWriter
        if not args.destdir:
            raise CmdlineError("Please provide a destination directory pointing to the root of the web output directory")
        writer = WebWriter(args.destdir)
    elif not args.type:
        from staticsite.check import Checker
        writer = Checker()
    else:
        raise CmdlineError("Output type {} is not supported".format(args.type))

    writer.write(site)


if __name__ == "__main__":
    try:
        main()
    except CmdlineError as e:
        print(e, file=sys.stderr)
        sys.exit(1)
